name: Prepare Data

on:
 workflow_dispatch:

permissions:
 contents: write
 pages: write
 id-token: write
concurrency:
 group: 'pages'
 cancel-in-progress: true
jobs:
 build:
  runs-on: ubuntu-latest
  env:
   NODE_ENV: PRODUCTION

  steps:
   - name: Checkout ðŸ›Žï¸
     uses: actions/checkout@v4
   - run: |
      apt-get update \
      && apt-get install -y wget gnupg \
      && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
      && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
      && apt-get update \
      && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
      && rm -rf /var/lib/apt/lists/*
   - name: Setup Bun ðŸ«“
     uses: oven-sh/setup-bun@v1
     with:
      bun-version: latest
   - name: Make Screenshots ðŸ“¦
     run: |
      bun install;
      cd webscraper;
      bun install;
      cd ..;
      bun run scripts/screenshot.ts
